version: '3.3'

services:
  canary:
    image: canary:dev
    privileged: true
    volumes:
      - ./:/input/:rw
    command:
      - cfg
      - --base=/input
      - --file=src/original.h
      - --unit=add
      # - generate
      # - --base=/input
      # - --file=src/original.h
      # - --test=tests
      # - --persist
