version: '3.3'

services:
  canary:
    image: canary:dev
    privileged: true
    volumes:
      - ./:/input/:rw
    command:
      - generate
      - --base=/input
      - --file=src/original.h
      - --persist
