# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Canary Workflow

on:
  push: # On every push, no matter the repository
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        rm -rf ./build/
        pip install black
        pip install pylint
        pip install mypy
    - name: Test with unittest
      run: python3 -m unittest discover -v src
    # - name: Pylint for unused imports # TODO maybe use pylint for another purpose? 
    #   run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
    - name: Mypy type checking 
      run: mypy --strict $(git ls-files '*.py')
    - name: Black code formatting
      run: black --diff --check $(git ls-files '*.py')
    # - uses: snyk/actions/setup@master
    # - name: Test dependencies with Snyk
    #   run: snyk test
    #   env:
    #     SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
    # - name: Monitor dependencies for security issues with Snyk
    #   run: snyk monitor
    #   env:
    #     SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
