# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Canary Workflow

on:
  push: # On every push, no matter the repository
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        rm -rf ./build/
        pip install black
        pip install pylint
    - name: Test with unittest
      run: python3 -m unittest discover -v src
    - name: Pylint for unused imports # TODO maybe use pylint for another purpose? 
      run: pylint --disable=all --enable=unused-argument --enable=global-statement --enable=global-variable-not-assigned --enable=used-before-assignment --enable=function-redefined --enable=abstract-class-instantiated --enable=invalid-unary-operand-type --enable=no-member --enable=undefined-variable --enable=undefined-loop-variable $(git ls-files '*.py')
    - name: Black code formatting 
      run: rickstaa/action-black@v1
    # - uses: snyk/actions/setup@master
    # - name: Test dependencies with Snyk
    #   run: snyk test
    #   env:
    #     SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
    # - name: Monitor dependencies for security issues with Snyk
    #   run: snyk monitor
    #   env:
    #     SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
